#!/bin/sh

export POSIXLY_CORRECT=yes
export LC_NUMERIC=en_US.UTF-8

# test whether there is redirected input
if ! test -t 0; then
    while IFS= read -r line; do
      LOG_FILES="$LOG_FILES$line\n"
    done
    # deleting the last "\n" empty line by means of NF(number of fields in a line)
    ## Sorry for such a coding style :(
    LOG_FILES=$(echo "$LOG_FILES" | awk -F ';' '{ if (NF == 0) {next}
                                                  else {print} }')
fi

print_help()
{
    echo "Usage: tradelog [-h|--help]"
	echo "       tradelog [FILTER...] [COMMAND] [LOG...]"
	echo ""
}

COMMAND=""
WIDTH=""
TICKER=""
# For -w option
COUNT=1
# parsing our possible parameters
while getopts :abt:w:h-: opts
do case "$opts" in
   a) echo "a";;
   b) echo "b";;
   t) TICKER=$TICKER"$OPTARG;"
      TFLAG=1;;
   w) if [ $COUNT -gt 0 ]  # more than one occurrence
        then
          WIDTH=$OPTARG
          if ! echo "$WIDTH" | grep -qE '^[0-9]+$'; then
              echo "WIDTH IS NOT INTEGER OR POSSITIVE"
              exit 1
          fi
          WFLAG=1
          COUNT=$(( $COUNT - 1 ))
     else
        echo "More occurrences of option than was expected"
        exit 1
    fi
    ;;
   h) print_help
      exit 0;;
   -) print_help
      exit 0;;
   *) echo "Invalid flag"
      exit 1;;
   esac
done

shift $(($OPTIND - 1))

# initialize value for the command and delete argument
case $1 in
  list-tick | profit | pos | last-price | hist-ord | graph-pos)
    COMMAND=$1
    shift
    ;;
esac

# unzipping our logs
while [ $# -gt 0 ]
  do
    case $1 in
      *.log.gz)
        LOG_FILES="$LOG_FILES$(gzip -d -c "$1")\n"
        shift
        continue
        ;;
      *.log)
        LOG_FILES="$LOG_FILES$(cat "$1")\n"
        shift
        continue
        ;;
      *)
        echo "Invalid argument"
        exit 1
        ;;
    esac
  done

# delete all empty lines
LOG_FILES=$(echo "$LOG_FILES" | sed '/^$/d')


# checking flags of filters
if [ "$TFLAG" = "1" ]; then
    LOG_FILES=$(echo "$LOG_FILES" | awk -F ';' -v last_price="$TICKER" ' last_price~ $2";" {print}')
fi

if [ "$COMMAND" = "list-tick" ]; then
    LOG_FILES=$(echo "$LOG_FILES" | awk -F ';' '{print $2}' | sort -u)
fi

if [ "$COMMAND" = "profit" ]; then
    PROFIT=$(echo "$LOG_FILES" | awk -F ';' 'BEGIN {bought=0; sold=0}
                                            {
                                            if ($3 == "buy")
                                                 {bought += ($4 * $6)}
                                            else {sold += ($4 * $6)}
                                            }
                                            END {printf("%.2f\n", sold - bought)}')
    echo $PROFIT
    exit 0
fi

if [ "$COMMAND" = "last-price" ]; then
    LAST_PRICE=$(echo "$LOG_FILES" | awk -F ';' '{ tickers[$2]=$4 }
                                                  END { for (last_price in tickers)
                                                            {
                                                            printf("%s %c %.2f\n", last_price, ":", tickers[last_price])
                                                            }
                                                       }' | sort -u)
    echo "$LAST_PRICE"
fi
#echo "$LOG_FILES"




# 1) to pick up flags for redirected input to output the logs
# 2) -a|-b   : Zly format casu a datumu (spravne ma byt YYYY-MM-DD HH:MM:SS)
# 3)